addSbtPlugin("nl.gn0s1s"          % "sbt-dotenv"               % "3.1.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.4")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.11.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.14.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.18.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.21.1")
